# Generated by Django 4.1.5 on 2023-03-21 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("onlinexam", "0004_uploadedexcel"),
        ("student", "0005_student_is_eligible"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "expiration_days",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "expiration_hours",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("is_attended", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onlinexam.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
