# Generated by Django 4.1.6 on 2023-03-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('asset_photo', models.ImageField(blank='True', null=True, upload_to='media/images/')),
                ('asset_owner', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=50)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('Asset_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
