# Generated by Django 4.1.6 on 2023-03-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_inform',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='asset_inform',
            name='status',
        ),
    ]
