# Generated by Django 4.1.5 on 2023-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assetapp", "0002_remove_asset_inform_published_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset_inform",
            name="asset_status",
            field=models.CharField(
                choices=[("Booked asset", "Booked asset"), ("Approved", "Approved")],
                max_length=20,
                null=True,
            ),
        ),
    ]
