# Generated by Django 4.1.6 on 2023-03-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_commentrating'),
        ('postapp', '0002_replypostrating'),
    ]

    operations = [
    ]
