# Generated by Django 4.1.6 on 2023-03-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_merge_0002_commentrating_0002_replypostrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='mention',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='posti',
            field=models.ImageField(blank='True', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank='True', upload_to='media/videos/'),
        ),
        migrations.DeleteModel(
            name='CommentRating',
        ),
    ]
