# Generated by Django 4.1.6 on 2023-03-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replypostrating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replypostrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentPost1',
        ),
        migrations.DeleteModel(
            name='ReplyPostRating',
        ),
    ]
