# Generated by Django 4.1.5 on 2023-03-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_coursepublication"),
        ("postapp", "0009_alter_post_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher.teacher",
            ),
        ),
    ]
