# Generated by Django 4.2 on 2023-06-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0011_alter_post_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posti',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, upload_to='media/videos/'),
        ),
    ]
