# Generated by Django 4.2 on 2023-07-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('job_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('Position', models.CharField(max_length=30)),
                ('resourcerequired', models.FloatField()),
                ('jd', models.TextField()),
                ('resourceremaining', models.FloatField()),
                ('r_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Freeze', 'Freeze')], default='open', max_length=20)),
                ('date_created', models.DateField(auto_now=True)),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='High', max_length=30)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('candidate_name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=4)),
                ('owner_name', models.CharField(max_length=30)),
                ('l1', models.CharField(max_length=30)),
                ('l2', models.CharField(max_length=30)),
                ('l3', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Offered', 'Profile Selected'), ('Rejected', 'Profile Rejected'), ('OnHold', 'Yet to upload to the client')], default='OnHold', max_length=20)),
                ('date_created', models.DateField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.recruiter')),
            ],
            options={
                'db_table': 'uploaded_files',
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('band', models.CharField(max_length=10)),
                ('ctc', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.company')),
            ],
        ),
    ]
