# Generated by Django 4.1.7 on 2023-05-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset_inform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("asset_id", models.CharField(max_length=100)),
                ("asset_owner", models.CharField(max_length=100)),
                ("asset_type", models.CharField(max_length=200)),
                ("Asset_date", models.DateTimeField(auto_now_add=True)),
                (
                    "asset_status",
                    models.CharField(
                        choices=[("BUFFER", "BUFFER"), ("IN-USE", "IN-USE")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_created", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=10, unique=True)),
                ("asset_ids", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AssetTransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetapp.asset_inform",
                    ),
                ),
            ],
        ),
    ]
