# Generated by Django 4.1.7 on 2023-05-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assetapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assettransferrequest",
            name="asset",
        ),
        migrations.DeleteModel(
            name="TransferRequest",
        ),
        migrations.AddField(
            model_name="asset_inform",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="asset_inform",
            name="requested_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="AssetTransferRequest",
        ),
    ]
