# Generated by Django 4.1.7 on 2023-05-23 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assetapp", "0002_remove_assettransferrequest_asset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="asset_Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Asset_inform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetapp.asset_inform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
