# Generated by Django 4.1.7 on 2023-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assetapp", "0003_asset_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset_inform",
            name="date_created",
        ),
        migrations.AlterField(
            model_name="asset_inform",
            name="Asset_date",
            field=models.DateTimeField(null=True),
        ),
    ]
