# Generated by Django 4.1.7 on 2023-05-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assetapp", "0002_remove_assettransferrequest_asset_and_more"),
        ("cridential", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="Asset_inform",
            field=models.ManyToManyField(blank=True, to="assetapp.asset_inform"),
        ),
    ]
