# Generated by Django 4.1.7 on 2023-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaveapp", "0002_applyleave_rejection_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="category",
        ),
        migrations.AlterField(
            model_name="applyleave",
            name="leave_type",
            field=models.CharField(
                blank=True,
                choices=[("EL", "Earned Leave")],
                max_length=20,
                null=True,
                verbose_name="Leave Type",
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="leave_type",
            field=models.CharField(
                blank=True,
                choices=[("EL", "Earned Leave")],
                max_length=20,
                null=True,
                verbose_name="Leave Type",
            ),
        ),
    ]
