# Generated by Django 4.2 on 2023-07-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_remove_holiday_category_alter_applyleave_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='work_from_home_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Work from Home Balance'),
        ),
    ]
