# Generated by Django 4.2 on 2023-07-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0004_leavebalance_work_from_home_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_from_home_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Work from Home Balance'),
        ),
    ]
