# Generated by Django 4.1.6 on 2023-03-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_videopublication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopublication',
            old_name='video',
            new_name='video_file',
        ),
    ]
