# Generated by Django 4.1.6 on 2023-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0008_post_teacher'),
        ('student', '0003_rename_video_videopublication_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='post',
            field=models.ManyToManyField(blank=True, to='postapp.post'),
        ),
    ]
