# Generated by Django 4.1.6 on 2023-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
