# Generated by Django 4.2 on 2023-06-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cridential', '0003_teacheruser_studentuser'),
        ('student', '0005_student_is_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopublication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cridential.studentuser'),
        ),
    ]
